Предобработка

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('../data/cars.csv')

In [3]:
data

,manufacturer_name,model_name,transmission,color,odometer_value,year_produced,engine_fuel,engine_has_gas,engine_type,engine_capacity,...,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,duration_listed
0,Subaru,Outback,automatic,silver,190000,2010,gasoline,False,gasoline,2.5,...,True,True,True,False,True,False,True,True,True,16
1,Subaru,Outback,automatic,blue,290000,2002,gasoline,False,gasoline,3.0,...,True,False,False,True,True,False,False,False,True,83
2,Subaru,Forester,automatic,red,402000,2001,gasoline,False,gasoline,2.5,...,True,False,False,False,False,False,False,True,True,151
3,Subaru,Impreza,mechanical,blue,10000,1999,gasoline,False,gasoline,3.0,...,False,False,False,False,False,False,False,False,False,86
4,Subaru,Legacy,automatic,black,280000,2001,gasoline,False,gasoline,2.5,...,True,False,True,True,False,False,False,False,True,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38526,Chrysler,300,automatic,silver,290000,2000,gasoline,False,gasoline,3.5,...,True,False,False,True,True,False,False,True,True,301
38527,Chrysler,PT Cruiser,mechanical,blue,321000,2004,diesel,False,diesel,2.2,...,True,False,False,True,True,False,False,True,True,317
38528,Chrysler,300,automatic,blue,777957,2000,gasoline,False,gasoline,3.5,...,True,False,False,True,True,False,False,True,True,369
38529,Chrysler,PT Cruiser,mechanical,black,20000,2001,gasoline,False,gasoline,2.0,...,True,False,False,False,False,False,False,False,True,490
38530,Chrysler,Voyager,automatic,silver,297729,2000,gasoline,False,gasoline,2.4,...,False,False,False,False,False,False,False,False,True,632

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38531 entries, 0 to 38530
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   manufacturer_name  38531 non-null  object
 1   model_name         38531 non-null  object
 2   transmission       38531 non-null  object
 3   color              38531 non-null  object
 4   odometer_value     38531 non-null  int64
 5   year_produced      38531 non-null  int64
 6   engine_fuel        38531 non-null  object
 7   engine_has_gas     38531 non-null  bool
 8   engine_type        38531 non-null  object
 9   engine_capacity    38521 non-null  float64
 10  body_type          38531 non-null  object
 11  has_warranty       38531 non-null  bool
 12  state              38531 non-null  object
 13  drivetrain         38531 non-null  object
 14  price_usd          38531 non-null  float64
 15  is_exchangeable    38531 non-null  bool
 16  location_region    38531 non-null  object
 17  number_of_photos   38531 non-null  int64
 18  up_counter         38531 non-null  int64
 19  feature_0          38531 non-null  bool
 20  feature_1          38531 non-null  bool
 21  feature_2          38531 non-null  bool
 22  feature_3          38531 non-null  bool
 23  feature_4          38531 non-null  bool
 24  feature_5          38531 non-null  bool
 25  feature_6          38531 non-null  bool
 26  feature_7          38531 non-null  bool
 27  feature_8          38531 non-null  bool
 28  feature_9          38531 non-null  bool
 29  duration_listed    38531 non-null  int64
dtypes: bool(13), float64(2), int64(5), object(10)
memory usage: 5.5+ MB

In [6]:
data.isnull().sum().sum()

10

In [5]:
data[data.isnull().any(1)]

C:\Users\Миханэйло\AppData\Local\Temp\ipykernel_16232\2405591308.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.any and Series.any will be keyword-only.
  data[data.isnull().any(1)]

,manufacturer_name,model_name,transmission,color,odometer_value,year_produced,engine_fuel,engine_has_gas,engine_type,engine_capacity,...,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,duration_listed
8782,Fiat,500,automatic,orange,27000,2013,electric,False,electric,NaN,...,True,False,True,True,True,False,True,True,True,77
9048,Fiat,500,automatic,orange,49000,2014,electric,False,electric,NaN,...,False,False,True,False,True,False,True,False,True,11
24226,Chevrolet,Volt,automatic,silver,168000,2013,electric,False,electric,NaN,...,False,False,True,False,False,False,True,True,True,6
25943,Nissan,Leaf,automatic,white,57357,2015,electric,False,electric,NaN,...,True,True,True,True,True,True,True,True,True,75
26203,Nissan,Leaf,automatic,blue,97400,2011,electric,False,electric,NaN,...,True,False,False,False,False,False,True,False,True,64
26222,Nissan,Leaf,automatic,white,50000,2014,electric,False,electric,NaN,...,True,False,False,False,True,False,True,True,False,18
26582,Nissan,Leaf,automatic,black,84000,2014,electric,False,electric,NaN,...,False,False,False,False,True,True,True,True,True,138
26914,Nissan,Leaf,automatic,black,84500,2013,electric,False,electric,NaN,...,True,False,True,False,True,True,True,True,True,58
27554,BMW,i3,automatic,white,54150,2015,electric,False,electric,NaN,...,True,True,True,False,True,True,True,True,True,18
29590,BMW,i3,automatic,other,67000,2018,electric,False,electric,NaN,...,True,True,True,True,True,True,True,True,True,57